---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: modules
  manifests_path: test/integration
  manifest: default/init.pp
  require_chef_omnibus: false
  require_chef_for_busser: false

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: opensuse-13.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04   
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
